name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup pyenv
        run: python3 -m venv .env
      - run: source .env/bin/activate
      - run: pip install -r TP1/miniproject/requirements.txt
      - run: pytest TP1/miniproject/
