name: GitHub Actions Demo
on: 
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY@L}" >>${GITHUB_ENV}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/miniproject
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ env.REPO }}/web_app:latest
          

      - name: Deploy model on the super VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.VM_CONNEXION_HOST }}
          username: ${{ vars.VM_CONNEXION_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            echo ${{ vars.VM_CONNEXION_USERNAME }}

            echo "Pulling latest Docker image..."
            docker pull ghcr.io/${{ env.REPO }}/web_app:latest

            echo "Stopping and removing existing container (if any)..."
            docker stop web_app || true
            docker rm web_app || true

            echo "Starting new container..."
            docker run -d --restart unless-stopped --name web_app -p ${{ vars.VM_DEPLOY_PORT }}:${{ vars.VM_DEPLOY_PORT }} ${{ env.REPO }}/web_app:latest
